import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const id = () => text("id").primaryKey();
const audit = { createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull() };

export const staff = sqliteTable("staff", { id: id(), email: text("email").notNull(), role: text("role", { enum: ["owner", "artist"] }).notNull(), artistId: text("artist_id"), active: integer("active", { mode: "boolean" }).notNull().default(true), ...audit }, (table) => [uniqueIndex("staff_email_unique").on(table.email)]);
export const customers = sqliteTable("customers", { id: id(), name: text("name").notNull(), email: text("email").notNull(), phone: text("phone").notNull(), ...audit });
export const appointments = sqliteTable("appointments", { id: id(), customerId: text("customer_id").notNull().references(() => customers.id), artistId: text("artist_id").references(() => staff.id), status: text("status").notNull().default("submitted"), preferredStartAt: text("preferred_start_at").notNull(), scheduledStartAt: text("scheduled_start_at"), scheduledEndAt: text("scheduled_end_at"), description: text("description").notNull(), revision: integer("revision").notNull().default(1), ...audit }, (table) => [index("appointments_artist_schedule").on(table.artistId, table.scheduledStartAt)]);
export const appointmentHistory = sqliteTable("appointment_history", { id: id(), appointmentId: text("appointment_id").notNull().references(() => appointments.id), actorId: text("actor_id").references(() => staff.id), status: text("status").notNull(), note: text("note"), createdAt: text("created_at").notNull() });
export const availabilityBlocks = sqliteTable("availability_blocks", { id: id(), artistId: text("artist_id").notNull().references(() => staff.id), startsAt: text("starts_at").notNull(), endsAt: text("ends_at").notNull(), reason: text("reason"), ...audit }, (table) => [index("availability_artist_interval").on(table.artistId, table.startsAt, table.endsAt)]);
export const mediaAssets = sqliteTable("media_assets", { id: id(), appointmentId: text("appointment_id").notNull().references(() => appointments.id), uploaderId: text("uploader_id").notNull().references(() => staff.id), objectKey: text("object_key").notNull(), state: text("state").notNull().default("pending"), approvedBy: text("approved_by").references(() => staff.id), approvedAt: text("approved_at"), ...audit }, (table) => [uniqueIndex("media_object_key_unique").on(table.objectKey)]);
export const calendarOutbox = sqliteTable("calendar_outbox", { id: id(), appointmentId: text("appointment_id").notNull().references(() => appointments.id), revision: integer("revision").notNull(), status: text("status").notNull().default("pending"), attempts: integer("attempts").notNull().default(0), nextAttemptAt: text("next_attempt_at").notNull(), ...audit }, (table) => [uniqueIndex("calendar_outbox_appointment_revision_unique").on(table.appointmentId, table.revision)]);
export const calendarProjection = sqliteTable("calendar_projection", { appointmentId: text("appointment_id").primaryKey().references(() => appointments.id), eventId: text("event_id").notNull(), revision: integer("revision").notNull(), stateHash: text("state_hash").notNull(), lastError: text("last_error"), updatedAt: text("updated_at").notNull() });
